apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  creationTimestamp: '2023-07-03T19:15:34Z'
  finalizers:
    - kubernetes.io/pv-protection
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:hostPath:
            .: {}
            f:path: {}
            f:type: {}
          f:persistentVolumeReclaimPolicy: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: rancher
      operation: Update
      time: '2023-07-03T19:15:34Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/bound-by-controller: {}
        f:spec:
          f:claimRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:namespace: {}
            f:resourceVersion: {}
            f:uid: {}
      manager: k3s
      operation: Update
      time: '2023-07-03T19:15:46Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:phase: {}
      manager: k3s
      operation: Update
      subresource: status
      time: '2023-07-03T19:15:46Z'
  name: rabbit-2
  resourceVersion: '120161'
  uid: aef9532d-782e-4619-aeba-5cd67aa1b12b
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 53687091200m
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-rabbitmq-1
    namespace: default
    resourceVersion: '119386'
    uid: 79b9bb3b-5c92-4225-8252-01641d09559e
  hostPath:
    path: /k8s-volume
    type: ''
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
status:
  phase: Bound
