apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: makima-ms-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://https://github.com/DenjiDev/makima-devops.git
    targetRevision: HEAD
    path: helm/makima-ms
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true