apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: makima-ms-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/DenjiDev/makima-engine'
    path: devops/helm
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: makima-ms
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
